import os
import pandas as pd
import subprocess
import psutil
import webbrowser


def create_excel(location="local"):
    filename = "Chiron_Output.xlsx"
    
    # Logic to find your actual Desktop path
    if location.lower() == "desktop":
        # This finds C:\Users\Nishaad\Desktop automatically
        base_path = os.path.join(os.path.expanduser("~"), "Desktop")
    else:
        base_path = os.getcwd() # Project folder
        
    full_path = os.path.join(base_path, filename)
    
    df = pd.DataFrame({"Data": ["Entry generated by Chiron"]})
    df.to_excel(full_path, index=False)
    return f"Created Excel sheet at {location}: {filename}"

def open_app(app_name):
    try:
        # Example: "open notepad" or "open browser"
        if "browser" in app_name.lower():
            webbrowser.open("https://google.com")
            return "Opening your web browser."
        else:
            subprocess.Popen(app_name.lower())
            return f"Launching {app_name}."
    except Exception:
        return f"I couldn't find the application {app_name}."

def get_system_stats(params=None):
    cpu = psutil.cpu_percent()
    ram = psutil.virtual_memory().percent
    return f"System check: CPU is at {cpu}% and RAM usage is at {ram}%."

# The Dispatcher Map
ACTION_MAP = {
    "CREATE_EXCEL": create_excel,
    "OPEN_APP": open_app,
    "SYSTEM_CHECK": get_system_stats
}